// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiEsRCu_xpcKIwGs7eMu6YdGAtEmHid0U',
    appId: '1:318365373266:web:4167f8cbccd6251631e08b',
    messagingSenderId: '318365373266',
    projectId: 'fruits-hub-2792d',
    authDomain: 'fruits-hub-2792d.firebaseapp.com',
    storageBucket: 'fruits-hub-2792d.firebasestorage.app',
    measurementId: 'G-Q6TRDTPK1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-K_7OdbR_K71gX2D_U94wR-dHPrDE6oM',
    appId: '1:318365373266:android:707ab6432d44b30631e08b',
    messagingSenderId: '318365373266',
    projectId: 'fruits-hub-2792d',
    storageBucket: 'fruits-hub-2792d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkQuhSDmJFEP8tmYwZ1PRxqZCPqyCzMGM',
    appId: '1:318365373266:ios:9600d0fd5df6481131e08b',
    messagingSenderId: '318365373266',
    projectId: 'fruits-hub-2792d',
    storageBucket: 'fruits-hub-2792d.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkQuhSDmJFEP8tmYwZ1PRxqZCPqyCzMGM',
    appId: '1:318365373266:ios:9600d0fd5df6481131e08b',
    messagingSenderId: '318365373266',
    projectId: 'fruits-hub-2792d',
    storageBucket: 'fruits-hub-2792d.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiEsRCu_xpcKIwGs7eMu6YdGAtEmHid0U',
    appId: '1:318365373266:web:6161d8cac914727d31e08b',
    messagingSenderId: '318365373266',
    projectId: 'fruits-hub-2792d',
    authDomain: 'fruits-hub-2792d.firebaseapp.com',
    storageBucket: 'fruits-hub-2792d.firebasestorage.app',
    measurementId: 'G-QXYB8XQS33',
  );
}
